name: CI

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v3
      - name: use NodeJs
        uses: actions/setup-node/@v3
        with:
          node-version: "latest"
      - run: npm install
      - run: npm run format
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
